# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore Catalog.API.csproj
RUN dotnet publish Catalog.API.csproj -c Release -o /app

# Stage 2: Runtime
FROM gcr.io/distroless/dotnet:9.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Catalog.API.dll"]

