name: Build and Test Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - Basket.API
          - Catalog.API
          - Ordering.API
          - Identity.API
          - Webhooks.API
          - Mobile.Bff.Shopping
        test_path:
          - tests/Basket.UnitTests
          - tests/Catalog.FunctionalTests
          - tests/Ordering.FunctionalTests
          - tests/Ordering.UnitTests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Debug Directory Structure
      run: |
        echo "Root directory structure:"
        ls -R

    - name: Build Docker Image
      run: |
        cd src/${{ matrix.service }}
        echo "Building Docker image for ${{ matrix.service }} in $(pwd)"
        docker build \
          -t ${{ matrix.service }}:latest \
          --build-arg DATABASE_URL="localhost" \
          --build-arg DATABASE_NAME="default_db" \
          --build-arg DATABASE_USER="default_user" \
          --build-arg DATABASE_PASSWORD="default_password" \
          --build-arg STORAGE_BUCKET_NAME="default_bucket" \
          --build-arg STORAGE_ACCESS_KEY="default_access_key" \
          --build-arg STORAGE_SECRET_KEY="default_secret_key" \
          --build-arg WEBHOOK_URL="https://webhook.example.com" \
          --build-arg EXTERNAL_API_KEY="default_api_key" .

    - name: Run Unit and Functional Tests
      run: |
        cd ${{ matrix.test_path }}
        echo "Running tests in $(pwd)"
        ls
        dotnet test --logger:trx
